### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Gottox** [Gottox/nson#1]
* [ ] automaticly detect parser to use
* [ ] the cmdline util should be able to parse arbitrary documents
* [ ] the cmdline util should serialize the parsed documents in other formats
* [ ] add nson_filter and nson_filter_thread
* [ ] document functions
